# Generated by Django 5.2.5 on 2025-11-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='전화번호')),
                ('verification_code', models.CharField(max_length=6, verbose_name='인증번호')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='발송 시간')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 완료 여부')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증 완료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('attempt_count', models.IntegerField(default=0, verbose_name='시도 횟수')),
            ],
            options={
                'verbose_name': '전화번호 인증',
                'verbose_name_plural': '전화번호 인증 목록',
                'db_table': 'phone_verification',
                'indexes': [models.Index(fields=['phone_number', 'sent_at'], name='phone_verif_phone_n_d3b6b8_idx')],
            },
        ),
    ]
