# Generated by Django 5.2.5 on 2025-11-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phoneverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
