# Generated by Django 5.2.5 on 2025-11-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kakao_refresh_token",
            field=models.TextField(
                blank=True,
                help_text="카카오 refresh_token (탈퇴 시 카카오 연결 끊기용)",
                null=True,
            ),
        ),
    ]
