# Generated by Django 5.2.5 on 2025-12-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_kakao_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="kakao_refresh_token",
        ),
    ]
