# Generated by Django 5.2.5 on 2025-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_kakao_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_sub',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
