# Generated by Django 5.2.5 on 2026-02-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_apple_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
