# Generated by Django 5.2.5 on 2026-06-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_terms_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_type', models.CharField(choices=[('sms', 'SMS'), ('octomo', 'OCTOMO')], default='sms', max_length=10)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('daily_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_verification',
                'indexes': [models.Index(fields=['phone_number', 'verification_type'], name='phone_verif_phone_n_bdb400_idx')],
            },
        ),
    ]
