# Generated by Django 5.2.5 on 2026-06-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
