# Generated by Django 5.2.5 on 2026-07-07 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_phoneverification_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.JSONField(default=list)),
                ('age_range', models.CharField(choices=[('10s', '10대'), ('20s', '20대'), ('30s', '30대'), ('40s', '40대'), ('50s', '50대'), ('60s+', '60대 이상')], max_length=10)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('N', '선택 안 함')], max_length=1)),
                ('exercise_frequency', models.CharField(choices=[('none', '거의 안 함'), ('1_2', '주 1~2회'), ('3_plus', '주 3회 이상')], max_length=10)),
                ('caffeine_sensitivity', models.CharField(choices=[('sensitive', '예민한 편'), ('normal', '보통'), ('none', '상관없음')], max_length=10)),
                ('sleep_hours', models.CharField(choices=[('8_plus', '8시간 이상'), ('5_7', '5~7시간'), ('1_4', '1~4시간')], max_length=10)),
                ('meal_regularity', models.CharField(choices=[('regular', '규칙적'), ('irregular', '불규칙한 편'), ('diet', '다이어트 중')], max_length=10)),
                ('alcohol_frequency', models.CharField(choices=[('none', '거의 안 함'), ('1_2', '주 1~2회'), ('3_plus', '주 3회 이상')], max_length=10)),
                ('smoking_status', models.CharField(choices=[('none', '비흡연'), ('smoking', '흡연'), ('quitting', '금연 중')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
                'db_table': 'user_profiles',
            },
        ),
    ]
