# Generated by Django 5.2.5 on 2026-07-07 09:34

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='goals',
            field=models.JSONField(default=list, validators=[users.models.validate_goals]),
        ),
    ]
