# Generated by Django 5.2.5 on 2026-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_bannerdetail_remove_banner_detail_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='bannerdetail',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='bannerdetail',
            unique_together={('banner', 'order')},
        ),
    ]
