# Generated by Django 5.2.5 on 2025-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_reviewreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreport',
            name='reason',
            field=models.CharField(choices=[('IRRELEVANT', '제품과 관련 없는 이미지 / 내용'), ('MISMATCH', '제품 미사용 / 리뷰 내용과 다른 제품 선택'), ('PROMOTION', '광고 홍보 / 거래 시도'), ('ABUSE', '욕설, 비속어가 포함된 내용'), ('PRIVACY', '개인 정보 노출')], max_length=32, verbose_name='신고 사유'),
        ),
    ]
