# Generated by Django 5.2.5 on 2025-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_reviewreport_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='추가 설명'),
        ),
    ]
