# Generated by Django 5.2.5 on 2025-09-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewreport_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewreport',
            name='detail',
        ),
    ]
