# Generated by Django 5.2.5 on 2025-10-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_review_updated"),
        ("review", "0005_remove_reviewreport_detail"),
    ]

    operations = []
