# Generated by Django 5.2.5 on 2025-10-03 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_merge_20250930_1128'),
        ('review', '0006_merge_20251002_0105'),
    ]

    operations = [
    ]
