# Generated by Django 5.2.5 on 2025-10-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0007_merge_20251003_0941"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="차단한 사용자 ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="차단 일시"),
                ),
                (
                    "blocked_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_users",
                        to="review.review",
                        verbose_name="차단된 리뷰",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_reviews",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "blocked_review"),
                        name="unique_blocked_review_per_user",
                    )
                ],
            },
        ),
    ]
