# Generated by Django 5.2.5 on 2025-10-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0008_blockedreview"),
    ]

    operations = []
