# Generated by Django 5.2.5 on 2025-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0009_auto_20251029_0146"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocker_user_id",
                    models.IntegerField(verbose_name="차단한 사용자 ID"),
                ),
                (
                    "blocked_user_id",
                    models.IntegerField(verbose_name="차단당한 사용자 ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="차단 일시"),
                ),
            ],
            options={
                "db_table": "blocked_users",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker_user_id", "blocked_user_id"),
                        name="unique_blocked_user_relationship",
                    )
                ],
            },
        ),
    ]
