# Generated by Django 5.2.5 on 2026-07-18 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0029_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='저장한 사용자')),
            ],
            options={
                'db_table': 'saved_recommendations',
            },
        ),
        migrations.CreateModel(
            name='SavedRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(verbose_name='성분 한 줄 소개')),
                ('reason', models.TextField(verbose_name='추천 이유')),
                ('fit_score', models.IntegerField(verbose_name='적합도')),
                ('rank', models.IntegerField(verbose_name='추천 순위')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_recommendation_items', to='products.ingredient')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.savedrecommendation')),
            ],
            options={
                'db_table': 'saved_recommendation_items',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='설문 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL, verbose_name='응답 사용자')),
            ],
            options={
                'db_table': 'user_surveys',
            },
        ),
        migrations.AddIndex(
            model_name='savedrecommendation',
            index=models.Index(fields=['user', '-created_at'], name='saved_recom_user_id_3a3aa3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedrecommendationitem',
            unique_together={('recommendation', 'rank')},
        ),
    ]
