# Generated by Django 5.2.5 on 2026-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='savedrecommendation',
            name='saved_recom_user_id_3a3aa3_idx',
        ),
        migrations.AddField(
            model_name='savedrecommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
