# Generated by Django 5.2.5 on 2026-07-21 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_savedrecommendation_saved_recom_user_id_3a3aa3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecommendation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='저장한 사용자'),
        ),
    ]
