# Generated by Django 5.2.5 on 2025-09-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='성분 이름')),
                ('englishIngredient', models.CharField(verbose_name='영어이름')),
                ('minRecommended', models.IntegerField(verbose_name='최소권장량')),
                ('maxRecommended', models.IntegerField(verbose_name='최대권장량')),
                ('effect', models.TextField(verbose_name='효과')),
                ('sideEffect', models.TextField(verbose_name='부작용')),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='제품 이름')),
                ('company', models.TextField(verbose_name='회사 이름')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('unit', models.TextField(verbose_name='단위')),
                ('piece', models.IntegerField(verbose_name='개수')),
                ('nutrients', models.TextField(verbose_name='영양정보')),
                ('viewCount', models.IntegerField(verbose_name='조회수')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='포함량')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productIngredients', to='products.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product')),
            ],
            options={
                'db_table': 'productIngredients',
            },
        ),
    ]
