# Generated by Django 5.2.5 on 2025-09-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='viewCount',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
