# Generated by Django 5.2.5 on 2025-09-12 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_viewcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
            ],
            options={
                'db_table': 'big_categories',
            },
        ),
        migrations.CreateModel(
            name='SmallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('bigCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smallCategories', to='products.bigcategory', verbose_name='대분류 외래키')),
            ],
            options={
                'db_table': 'small_categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='products.product', verbose_name='제품 외래키')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='products.smallcategory', verbose_name='카테고리 외래키')),
            ],
            options={
                'db_table': 'category_products',
            },
        ),
    ]
