# Generated by Django 5.2.5 on 2025-09-12 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bigcategory_smallcategory_categoryproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productingredient',
            table='products_ingredients',
        ),
    ]
