# Generated by Django 5.2.5 on 2025-09-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productingredient_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productingredient',
            table='product_ingredients',
        ),
    ]
