# Generated by Django 5.2.5 on 2025-09-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productingredient_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='maxRecommended',
            field=models.CharField(verbose_name='최대권장량'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='minRecommended',
            field=models.CharField(verbose_name='최소권장량'),
        ),
    ]
