# Generated by Django 5.2.5 on 2025-09-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_nutrients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='amount',
            field=models.CharField(verbose_name='포함량'),
        ),
    ]
