# Generated by Django 5.2.5 on 2025-09-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='englishIngredient',
            field=models.CharField(max_length=100, verbose_name='영어이름'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='maxRecommended',
            field=models.CharField(max_length=50, verbose_name='최대권장량'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='minRecommended',
            field=models.CharField(max_length=50, verbose_name='최소권장량'),
        ),
    ]
