# Generated by Django 5.2.5 on 2025-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_ingredient_englishingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='amount',
            field=models.CharField(max_length=50, verbose_name='포함량'),
        ),
    ]
