# Generated by Django 5.2.5 on 2025-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.TextField(verbose_name='식품의 유형'),
        ),
    ]
