# Generated by Django 5.2.5 on 2025-09-13 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_views', to='products.product')),
            ],
            options={
                'db_table': 'product_daily_views',
                'indexes': [models.Index(fields=['date'], name='product_dai_date_2173e8_idx'), models.Index(fields=['product', 'date'], name='product_dai_product_28f376_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
