# Generated by Django 5.2.5 on 2025-10-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productdailyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='piece',
            field=models.TextField(verbose_name='개수'),
        ),
    ]
