# Generated by Django 5.2.5 on 2025-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='sideEffect',
            field=models.TextField(blank=True, null=True, verbose_name='부작용'),
        ),
    ]
