# Generated by Django 5.2.5 on 2025-11-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_ingredient_sideeffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupang',
            field=models.TextField(blank=True, null=True, verbose_name='쿠팡 링크'),
        ),
    ]
