# Generated by Django 5.2.5 on 2025-12-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_coupang'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='mainIngredient',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='주성분이름'),
        ),
    ]
