# Generated by Django 5.2.5 on 2025-12-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_ingredient_mainingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='englishIngredient',
        ),
    ]
