# Generated by Django 5.2.5 on 2025-12-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_ingredient_englishingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='effect',
            field=models.JSONField(default=list, verbose_name='효과'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sideEffect',
            field=models.JSONField(default=list, verbose_name='부작용'),
        ),
    ]
