# Generated by Django 5.2.5 on 2025-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_convert_effect_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='effect',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='효과'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='maxRecommended',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='최대권장량'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='minRecommended',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='최소권장량'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='sideEffect',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='부작용'),
        ),
    ]
