# Generated by Django 5.2.5 on 2025-12-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_ingredient_effect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
