# Generated by Django 5.2.5 on 2025-12-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_product_piece_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='기타 원료명')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_ingredients', to='products.product', verbose_name='제품')),
            ],
            options={
                'db_table': 'other_ingredients',
                'indexes': [models.Index(fields=['product'], name='other_ingre_product_908d2d_idx')],
            },
        ),
    ]
