# Generated by Django 5.2.5 on 2026-01-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_otheringredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOtherIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'product_other_ingredients',
            },
        ),
        migrations.RemoveIndex(
            model_name='otheringredient',
            name='other_ingre_product_908d2d_idx',
        ),
        migrations.RemoveField(
            model_name='otheringredient',
            name='product',
        ),
        migrations.AlterField(
            model_name='otheringredient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='기타 원료명'),
        ),
        migrations.AddField(
            model_name='productotheringredient',
            name='other_ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.otheringredient', verbose_name='기타 원료'),
        ),
        migrations.AddField(
            model_name='productotheringredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_other_ingredients', to='products.product', verbose_name='제품'),
        ),
        migrations.AddIndex(
            model_name='productotheringredient',
            index=models.Index(fields=['product'], name='product_oth_product_c3bb14_idx'),
        ),
        migrations.AddIndex(
            model_name='productotheringredient',
            index=models.Index(fields=['other_ingredient'], name='product_oth_other_i_426c88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productotheringredient',
            unique_together={('product', 'other_ingredient')},
        ),
    ]
