# Generated by Django 5.2.5 on 2026-02-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallcategory',
            name='bigCategory',
        ),
        migrations.CreateModel(
            name='MiddleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='카테고리')),
                ('big_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_categories', to='products.bigcategory', verbose_name='대분류 외래키')),
            ],
            options={
                'db_table': 'middle_categories',
            },
        ),
        migrations.AddField(
            model_name='smallcategory',
            name='middle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_categories', to='products.middlecategory', verbose_name='중분류 외래키'),
        ),
    ]
