# Generated by Django 5.2.5 on 2026-02-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_smallcategory_bigcategory_middlecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallcategory',
            name='middle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small_categories', to='products.middlecategory', verbose_name='중분류 외래키'),
        ),
    ]
