# Generated by Django 5.2.5 on 2026-02-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_smallcategory_middle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyPoints', models.JSONField(blank=True, default=list, verbose_name='핵심 포인트')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='출처')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='products.ingredient')),
            ],
            options={
                'db_table': 'ingredient_guides',
            },
        ),
    ]
