# Generated by Django 5.2.5 on 2026-04-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_ingredientguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('products', models.JSONField(default=list)),
                ('ingredients', models.JSONField(default=dict)),
                ('pi_rows', models.JSONField(default=list)),
                ('unmatched', models.JSONField(default=list)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'import_jobs',
            },
        ),
    ]
