# Generated by Django 5.2.5 on 2026-08-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='goals',
            field=models.JSONField(blank=True, default=list, verbose_name='추천 목표'),
        ),
    ]
