# Generated by Django 5.2.5 on 2026-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_ingredient_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='해시태그'),
        ),
    ]
